# Generated by Django 6.0 on 2026-09-24 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('uuid_referencia', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('entidade', models.CharField(max_length=50)),
                ('detalhes', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.familiaworkspace')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(max_length=50)),
                ('entidade', models.CharField(max_length=50)),
                ('uuid_entidade', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('dados_novos', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.familiaworkspace')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('ADMIN', 'Administrador'), ('COLABORADOR', 'Colaborador'), ('LEITOR', 'Leitor')], default='LEITOR', max_length=20)),
                ('aderiu_em', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.familiaworkspace')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'familia')},
            },
        ),
    ]
