# Generated by Django 6.0 on 2026-07-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('acao', models.CharField(max_length=50)),
                ('entidade', models.CharField(max_length=50)),
                ('detalhes', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
