# Generated by Django 6.0 on 2026-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('tipo_acao', models.CharField(max_length=50)),
                ('entidade', models.CharField(max_length=50)),
                ('uuid_entidade', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('dados_novos', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
